# Use Node.js 22 LTS on Alpine
# Use your local base image by its digest
FROM localbase:latest

# Set working directory
WORKDIR /home/appuser

# Expose port 4000
EXPOSE 4000

# Default command (you can change this)
CMD ["bash"]
